services:
    db:
        container_name: postgres_db
        image: postgres
        ports:
            - 5001:5432
        environment:
            POSTGRES_PASSWORD: root
            POSTGRES_USER: root

    pgAdmin:
        image: dpage/pgadmin4
        ports:
            - 5000:80
        environment:
            PGADMIN_DEFAULT_EMAIL: root@gmail.com
            PGADMIN_DEFAULT_PASSWORD: root
